### ISSUE TITLE
Issue 6 for Milestone 3: Training the Model (Lab 5-8)

### ISSUE THREAD

**Issue by UzairFarooq1** [UzairFarooq1/BI-Project#5]
- [x] Discover Patterns
- [x] Set Minimum Support and Confidence Thresholds that is appropriate to obtain the rules
- [x] Generate Association Rules
- [x] Filter and Refine Rules
- [x] Visualize Rules

**Comment by UzairFarooq1** [comment]
Completed Issue 6
